WebRole1/Controllers/MusicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using WebRole1.Component;
using WebRole1.Component.DataStorage;
using WebRole1.Component.Music;
using WebRole1.Models;
using WebRole1.Models.JamendoModels;
using Microsoft.AspNet.Identity;
using System.Security.Claims;

namespace WebRole1.Controllers
{
    public class MusicController : Controller
    {
        private IJamendoComponent jamendoComponent;
        private IUserComponent userComponent;
        private IMusicDatabaseComponent musicDatabaseComponent;
        private IMusicPlaylistComponent musicPlaylistComponent;

        public MusicController (IJamendoComponent jamendoComponent, IUserComponent userComponent, IMusicDatabaseComponent musicDatabaseComponent, IMusicPlaylistComponent musicPlaylistComponent)
        {
            this.jamendoComponent = jamendoComponent;
            this.userComponent = userComponent;
            this.musicDatabaseComponent = musicDatabaseComponent;
            this.musicPlaylistComponent = musicPlaylistComponent;
        }

        // GET: Music
        public ActionResult SearchTitle(string trackname = null)
        {
            if (trackname != null)
            {
                ViewBag.searchedTrack = trackname;
                ViewBag.foundedTracks = jamendoComponent.FindTrack(trackname);
            }

            return View("SearchTitleView");
        }

        public ActionResult DisplayTitle(string trackID = null)
        {
            string username = User.Identity.GetUserName();
            User user;

            if (!this.userComponent.getUserByName(username, out user))
            {
                ViewBag.error ="Sorry you must be identified to reach this feature!";
                return View("Play");
            }

            if (trackID == null)
            {
                ViewBag.error = "Sorry buy you need to provide a track to play";
            }

            JamendoTrack track = jamendoComponent.GetTrackById(trackID);

            if (track == null)
            {
                ViewBag.error = "Oups ! We can't find this track !";
                return View("Play");
            }

            ViewBag.currentTrack = track;

            //Added music to user history
            this.musicDatabaseComponent.addListenMusic(user, track.id);

            //Display if the music was already added to playlist
            ViewBag.tittleAddedPlaylist = musicPlaylistComponent.getPlaylist(user).Any( p => p.id == track.id);


            ViewBag.foundedTracks = musicPlaylistComponent.getPlaylist(user).DistinctBy(p => p.id).ToList();

            return View("Play");
        }

        [System.Web.Mvc.HttpGet]
        public JsonResult completeTitle(string title)
        {
            return Json(jamendoComponent.AutoCompleteTittle(title),JsonRequestBehavior.AllowGet);
        }


    }
}

WebRole1/Controllers/MusicTopController.cs
using System.Web.Mvc;
using WebRole1.Component.Music;

namespace WebRole1.Controllers
{
    public class MusicTopController : Controller
    {
        private IMusicClassementComponent musicClassementComponent;

        public MusicTopController(IMusicClassementComponent musicClassementComponent)
        {
            this.musicClassementComponent = musicClassementComponent;
        }

        public ActionResult DisplayTopTen()
        {
            
            ViewBag.TopTen = musicClassementComponent.DisplayTopTenMusic();

            return View("TopTen");
        }
    }
}

WebRole1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon application ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                    <a id="loginLink" style="color:lightgreen">
                   
                        <img src="\Content\images\Logo.png" height: "100px" ; width="100" ; alt="Logo Supinfy" />
                    </a>
                @Html.ActionLink("Accueil", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Accueil", "Index", "Home")</li>
                    <li>@Html.ActionLink("À propos", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    @if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Users List", "ListUsers", "Account")</li>
                        <li>@Html.ActionLink("Search Title", "SearchTitle", "Music")</li>
                        <li>@Html.ActionLink("Top 10", "DisplayTopTen", "MusicTop")</li>

                    }

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Supinfy </p>
        </footer>
    </div>

</body>
</html>